### ISSUE TITLE
[Quarto] couldn't find appropriate code runner for language: python

### ISSUE THREAD

**Issue by andy941** [quarto-dev/quarto-nvim#102]
Hi,

I have installed molten and it works correctly in quarto files, meaning that I can run lines/selections and see the output in line as expected. If I try to use Quarto to run cells however:
``` lua
lua require("quarto.runner").run_cell()
```
I get the error:
```
[Quarto] couldn't find appropriate code runner for language: python
```

Also weird is that I can see only part of the commands in the README:

```
can see this ones:
QuartoPreview
QuartoClosePreview
QuartoHelp <..>
QuartoActivate
QuartoHover

Can't see these:
QuartoDiagnostics
QuartoSend
QuartoSendAbove
QuartoSendBelow
QuartoSendAll
QuartoSendLine
```

My config:
``` lua
require("quarto").setup({
	debug = false,
	closePreviewOnExit = true,
	lspFeatures = {
		enabled = true,
		languages = { "r", "python", "julia", "bash" },
		chunks = "curly", -- 'curly' or 'all'
		diagnostics = {
			enabled = true,
			triggers = { "BufWritePost" },
		},
		codeRunner = {
			enabled = true,
			default_method = { "molten" }, -- 'molten' or 'slime'
			--ft_runners = {}, -- filetype to runner, ie. `{ python = "molten" }`.
			-- Takes precedence over `default_method`
			never_run = { "yaml" }, -- filetypes which are never sent to a code runner
		},
		completion = {
			enabled = true,
		},
	},
	keymap = {
		hover = "K",
		definition = "gD",
		rename = "<leader>R",
		references = "gr",
	},
})
```

I tried to troubleshoot but I can't figure out what is going wrong, I also tried to flip the debug to true but the errors don't get more verbose. When I run QuartoActivate nothing seems to happen (no feedback) if that matters.
Do you have any input on what might be going wrong here? Is there a way get more debug output?

I would really love to get this to work and send cells with one command, which I can't figure out how to do with molten.

Thank you,
Andrea

**Comment by jmbuhr** [comment]
Looks like you assigned a table instead of a string as the default code runner option. Does it work if you remove the curly braces around 'molten'?

**Comment by andy941** [comment]
Yes that Is the first thing I tried, then I tried passing a table just to make sure it wasn't that and I forgot to change it back before copy-paste. Same error in both cases.

**Comment by jmbuhr** [comment]
@benlubas Do you have a hunch what is happening here?

**Comment by benlubas** [comment]
This could be an issue with the way otter is setup. 

Can you include any otter config? Or just confirm that it's installed and that you don't call it's setup method?

@andy941

**Comment by benlubas** [comment]
I have some more time now to look into this. The commands are interesting. `QuartoDiagnostics` doesn't exist (anymore?).

Not seeing the send commands suggests that the code runner isn't enabled...

And I see the problem. This chunk of config shouldn't be inside `lspFeatures`
```
		codeRunner = {
			enabled = true,
			default_method = { "molten" }, -- 'molten' or 'slime'
			--ft_runners = {}, -- filetype to runner, ie. `{ python = "molten" }`.
			-- Takes precedence over `default_method`
			never_run = { "yaml" }, -- filetypes which are never sent to a code runner
		},
```

**Comment by andy941** [comment]
Thanks for the help,`QuartoSendCell` is now showing up and I can use it to send only python cells after `MoltenInit python3`.

QuartoDiagnostics is still not showing up. The completion and lsp only works for python. I am not sure what is going wrong here especially if I can't see the diagnostics. I can confirm otter is installed and I am not calling setup. As a sanity check I tried to uninstall otter and I get the error `module no found` as expected, so it's not silently failing.

example quarto code below:

---
title: "Quarto Basics"
format:
  html:
    code-fold: true
jupyter: python3
---

For a demonstration of a line plot on a polar axis, see @fig-polar.


```{bash}
grep -v "/" ./tmp.ipynb
```


```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r);
ax.set_rticks([0.5, 1, 1.5, 2]);
ax.grid(True);
plt.show()
```

**Comment by andy941** [comment]
I use Packer and I don't need the full kickstarter configuration, is there a more minimal configuration to get the basic stuff going with quarto-nvim and otter? Molten can be dealt separately as I think if it works on its own it should work with quarto-nvim as well in most cases. It would help in troubleshooting.

**Comment by jmbuhr** [comment]
The QuartoDiagnostics command is no longer necessary, you should see diagnostics without it if configured correctly. Check out the quarto.lua file in the kickstarter for the relevant pieces (language servers, nvim-cmp with otter source, quarto-nvim, treesitter parsers). Other than that it really depends on what you consider basic stuff.

**Comment by benlubas** [comment]
the `:QuartoDiagnostics` command doesn't exist in code, I think that it's leftover in the readme from previous versions of the plugin, so I'm not surprised that a command doesn't show. Do you see actual diagnostics from your python language server? for example, when using pyright I see errors if I have an unused import
![image](https://github.com/quarto-dev/quarto-nvim/assets/56943754/b4911f29-f242-41b2-baf0-3f6388b6166a)

I will say that sometimes the pyright LS takes some time to spin up, and diagnostics will only show up on buffer write, so it might see like it doesn't work, but it should.

The fact that LSP and is working for python is a good sign that this is working. What other languages are you trying to use LSP/completion with? You have to make sure those languages are in the languages tables that you pass to the lsp configuration in `setup()`, and that you have a language server for that language available.

**Comment by andy941** [comment]
Thank you both for taking the time to help me.

I have completion + diagnostics + molten working perfectly in code python code blocks. If for example I have a code bash code block that does not work at all. Molten will try to run it as python code (the only kernel I can see is python3, but that might be a molten issue) but also diagnostics and completion don't work. If I open a bash file the LSP works as expected of course.

By basic stuff I mean having a minimal config that is supposed to at least get me LSP and completion for each code block.  Int the kickstarter config there is a lot of stuff that is nice to have but I have trouble distinguishing the core stuff. It might be me and it might be the fact that I am not familiar with lazy.nvim so I am missing something. I would really love to get this plugin to work but I am out of ideas.

**Comment by andy941** [comment]
Also LspInfo shows only pyright as active. It is not attached to the buffer but I guess it is attached to the hidden buffer with the python code

**Comment by andy941** [comment]
Ok I got an improvement, R code blocks show diagnostics and completion, bash blocks still don't. If I run the R code block with the R kernel it says "no lines in buffer" and nothing happens.

Am I supposed to install a kernel for each language, init them all and then choose the right one everytime I run a block or there is a better way? Maybe in the kickstarter-config?

**Comment by andy941** [comment]
The QuartoPreview works as expected.

**Comment by benlubas** [comment]
You do have to install a kernel for each language, that's just how it works. Similarly you have to install a language server for each language you want auto complete for. 

For bash commands, you can run them with the ipython kernel with the `!` prefix. 

If you have multiple running kernels with molten then you have to select which one to send to. This is something that quarto-nvim could handle and something I eventually want to implement, but I haven't gotten around to it.

Until I get around to that I'd recommend sticking to single language notebooks if you don't want to always have to specify the kernel.

Glad you have everything working!

**Comment by andy941** [comment]
I see thank you for the explanation, it's a lot more clear now. Not having to specify would be a great improvement, I use mainly python these days but I have a soft spot for ggplot, it just so nice...

For now it works wonders and allows me to have a Jupyter notebook style development (and much more with Quarto!) in neovim, you have no idea how many plugins I have tried before finding this so thank you!

Doo you think it would be possible in the future to sync the QuartoPreview with the  cursor position in the same way that [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim) does? Or it is impossible with the way that Quarto rendering works? For me that would even render molten almost redundant, especially because the hidden buffer allows name to use the debugger (great stuff there, I just haven't figure out how to access the damn buffer haha).

**Comment by jmbuhr** [comment]
Syncing the preview is possible in theory (happy about PRs if you want to look into this).

Try `:ls!` to list also hidden buffers, including the otter buffers. Just don't modify it directly, it would be overwritten by changes in the qmd anyways.

For multi-language setups I personally prefer simple nvim integrated terminals and sending code to them with vim-slime as shown in the config and videos (https://youtube.com/playlist?list=PLabWm-zCaD1axcMGvf7wFxJz8FZmyHSJ7&si=YRxVaTus7upabr51).
