### ISSUE TITLE
Formatting cells

### ISSUE THREAD

**Issue by andy941** [quarto-dev/quarto-nvim#104]
Is it possible to have formatting for the code in cells? I use formatter.nvim for all my formatting for example, is there a way to get it to format each code block with the right formatter? If not for the whole buffer just something like "format cell" would be amazing.

**Comment by jmbuhr** [comment]
Yes, that's a recent addition. Usage: https://youtu.be/iNe88IZplYM?t=140 Config: https://github.com/quarto-dev/quarto-nvim/blob/0a35b3890e9d723b730506d7d8b3ba3d0d6aae2e/lua/quarto/config.lua#L30

**Comment by jmbuhr** [comment]
Only works if the actual language server comes with a formatter though, not an external one that expects to change real files on disk. So it works for e.g. R or python-language-server with black plugin, but not pyright

**Comment by andy941** [comment]
Ah thank you for pointing that option out. I think at least for black it takes stdin input. That is how formatter.nvim works afaik, it takes an input text, the whole buffer or some lines, and runs the job (i.e. runs black). It then checks you haven't changed the buffer  before putting the formatted code back in.

**Comment by andy941** [comment]
I like to have control of all my formatters in one place, not many lsp have formatting. I am experimenting with cbfmt formatter as described in [this thread](https://github.com/mhartington/formatter.nvim/issues/176) and it works pretty well (can be used with something other than formatter.nvim). It works very well so far, I think it runs in parallel the codeblocks so should be pretty fast. I have not tried a big file though. 

Wanted to leave this here, it might help some folks in the future.

THank you for your answer, I need to look into treesitter more, I know absolutely nothing about leveraging the text objects.
