### ISSUE TITLE
Error with previewing plots.

### ISSUE THREAD

**Issue by mehmetcanbudak** [quarto-dev/quarto-nvim#105]
Can't plot matplotlib stuff.

The python functions of print and such works but when I try the trial code from the website  get an error about pillow library and imaging extension.

Starting python3 kernel...Done

Executing 'deneme.ipynb'
  Cell 1/1: ''...ERROR: 

An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()
------------------

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import matplotlib.pyplot as plt
      2 import numpy as np
      3 from PIL import Image

File ~/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py:161
    157 from packaging.version import parse as parse_version
    159 # cbook must import matplotlib only within function
    160 # definitions, so it is safe to import from it here.
--> 161 from . import _api, _version, cbook, _docstring, rcsetup
    162 from matplotlib.cbook import sanitize_sequence
    163 from matplotlib._api import MatplotlibDeprecationWarning

File ~/anaconda3/lib/python3.11/site-packages/matplotlib/rcsetup.py:27
     25 from matplotlib import _api, cbook
     26 from matplotlib.cbook import ls_mapper
---> 27 from matplotlib.colors import Colormap, is_color_like
     28 from matplotlib._fontconfig_pattern import parse_fontconfig_pattern
     29 from matplotlib._enums import JoinStyle, CapStyle

File ~/anaconda3/lib/python3.11/site-packages/matplotlib/colors.py:52
     49 from numbers import Real
     50 import re
---> 52 from PIL import Image
     53 from PIL.PngImagePlugin import PngInfo
     55 import matplotlib as mpl

File ~/anaconda3/lib/python3.11/site-packages/PIL/Image.py:82
     73 MAX_IMAGE_PIXELS = int(1024 * 1024 * 1024 // 4 // 3)
     76 try:
     77     # If the _imaging C module is not present, Pillow will not load
.
     78     # Note that other modules should not refer to _imaging directly
;
     79     # import Image and use the Image.core variable instead.
     80     # Also note that Image.core is not a publicly documented interf
ace,
     81     # and should be considered private and subject to change.
---> 82     from . import _imaging as core
     84     if __version__ != getattr(core, "PILLOW_VERSION", None):
     85         msg = (
     86             "The _imaging extension was built for another version o
f Pillow or PIL:\n"
     87             f"Core version: {getattr(core, 'PILLOW_VERSION', None)}
\n"
     88             f"Pillow version: {__version__}"
     89         )

ImportError: dlopen(/Users/mehmetcanbudak/anaconda3/lib/python3.11/site-pac
kages/PIL/_imaging.cpython-311-darwin.so, 0x0002): Library not loaded: @rpa
th/libtiff.5.dylib
  Referenced from: <865BA80B-4617-3103-AC5E-6873C17F99FD> /Users/mehmetcanb
udak/anaconda3/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin
.so
  Reason: tried: '/Users/mehmetcanbudak/anaconda3/lib/python3.11/site-packa
ges/PIL/../../../libtiff.5.dylib' (no such file), '/Users/mehmetcanbudak/an
aconda3/lib/python3.11/site-packages/PIL/../../../libtiff.5.dylib' (no such
 file), '/Users/mehmetcanbudak/anaconda3/bin/../lib/libtiff.5.dylib' (no su
ch file), '/Users/mehmetcanbudak/anaconda3/bin/../lib/libtiff.5.dylib' (no 
such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libt
iff.5.dylib' (no such file, not in dyld cache)

**Comment by jmbuhr** [comment]
That looks like a python/dependency issue, not a Quarto or Neovim issue. Check the system dependencies that matplotlib may have on your operating system.
