### ISSUE TITLE
Go to next/previous code cell

### ISSUE THREAD

**Issue by serhez** [quarto-dev/quarto-nvim#106]
Is there any way to configure a mapping (e.g., `]c` and `[c`) to go to the previous/next code cells? Is there a quarto function I could use for that? Thanks!

**Comment by jmbuhr** [comment]
Yes. Personally, I use `]]` (see https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/4bb2c1f30d5282720b9cde39c33537b59fd33ada/lua/plugins/quarto.lua#L98 in combination with https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/main/after/queries/markdown/textobjects.scm)

**Comment by serhez** [comment]
Works wonders, thank you!
