### ISSUE TITLE
Tangle Code Block

### ISSUE THREAD

**Issue by catethos** [quarto-dev/quarto-nvim#107]
The readme mentioned the code block can be exported as a script, but I can't find any documentation on it.

**Comment by jmbuhr** [comment]
This readme does not mention that (your statement seems a bit contradictory, either it is mentiond and thus there is a form of documentation or it is not mentioned), but I assume you are referring to `otter.export` from https://github.com/jmbuhr/otter.nvim/blob/b4f4a1bcddfe91ed342c86c72e8d156780289552/lua/otter/keeper.lua#L323C53-L323C53

Usage example: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/4bb2c1f30d5282720b9cde39c33537b59fd33ada/lua/config/keymap.lua#L171-L172C70
