### ISSUE TITLE
Error in export file name

### ISSUE THREAD

**Issue by catethos** [quarto-dev/quarto-nvim#108]
hi, shouldn't the path here contains a '.' before the file extension ?

https://github.com/jmbuhr/otter.nvim/blob/b4f4a1bcddfe91ed342c86c72e8d156780289552/lua/otter/keeper.lua#L307C45-L307C54

**Comment by jmbuhr** [comment]
good catch, thanks!

**Comment by jmbuhr** [comment]
fixed in the latest otter.nvim release :)
