### ISSUE TITLE
Feature Request: Improved Quarto File Preview Functionality

### ISSUE THREAD

**Issue by Aman9das** [quarto-dev/quarto-nvim#112]
### Current Behaviour

Currently, the `:QuartoPreview` and `<leader>qp>` commands are available for previewing the current Quarto project. However, there isn't a direct way to preview the currently open `.qmd` file specifically.

### Expected Behaviour

It would be beneficial to have a dedicated command for previewing the currently active `.qmd` file. This would streamline the process and enhance efficiency for users working with individual Quarto files within a project.

### Suggestions

Introducing a command like `:QuartoFile` and/or `<leader>qf` would provide a convenient solution for previewing the currently open Quarto file without the need to navigate through the entire project. This enhancement would improve user experience and productivity when working on specific Quarto documents within a project.

**Comment by jmbuhr** [comment]
The preview server automatically navigates to the last-modifed and saved file by default.

**Comment by Aman9das** [comment]
Thanks!

I was having issues previewing default type quarto projects. Creating keymap to ":Quarto preview %” fixed it.
