### ISSUE TITLE
Hard and soft dependencies

### ISSUE THREAD

**Issue by undefined-landmark** [quarto-dev/quarto-nvim#117]
Hi,

Big fan of nvim and quarto. Thanks for all your work on this plugin, documentation and videos.
I enjoy setting up my nvim config as simple as possible, only adding the things I miss. Therefore I started by adding only `quarto-nvim`. This doesn't work because of the hard dependencies on `otter`, `nvim-cmp` and some more. Or did I miss something? The integration is of course very nice, but making the integration optional might be even nicer? Curious to hear your thoughts, as you thought about it longer than I did.

As far as I can judge with a quick look at the source `QuartoPreview`, `QuartoClosePreview` and `QuartoHelp` for example do not depend on any other plugins. Maybe extending the configuration would make it possible to load only those independent commands? I'm willing to contribute and setup an example if wanted.

**Comment by undefined-landmark** [comment]
Thanks for the quick reply. I tried to follow the documentation, that links here https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/main/lua/plugins/quarto.lua. The following should work?

```
require("lazy").setup({
    {
        "quarto-dev/quarto-nvim",
        opts = {
            lspFeatures = {
                enabled = false
            }
        }
    }
})
```
If I run `nvim --clean -u init.lua` with init.lua containing the following I receive errors saying "module otter not found":
```
-- Bootstrap

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)


-- Setup plugins

require("lazy").setup({
    {
        "quarto-dev/quarto-nvim",
        opts = {
            lspFeatures = {
                enabled = false
            }
        }
    }
})
```

**Comment by jmbuhr** [comment]
Thanks for the quick reprex. With https://github.com/quarto-dev/quarto-nvim/commit/5336b86dc3d0517075debe8906671daeeab9f5ed quarto-nvim now only requires otter when its actually being used. `nvim-lspconfig` is still a requirement for QuartoPreview, as it brings helpful functions to find the project root.

Note that if you only need  to start a preview server, you don't really need this plugin. You can just make a keybinding like

```lua
vim.keymap.set('n', '<leader>qp', "<cmd>split | terminal quarto preview %<cr>", { silent = true })
```
