### ISSUE TITLE
quarto-nvim using wrong python on ios

### ISSUE THREAD

**Issue by Mayur1009** [quarto-dev/quarto-nvim#120]
Hi, 

I am running this[matplotlib demo](https://quarto.org/docs/computations/python.html). I have a python virtual environment activated. When I run the `quarto preview a.qmd` and `quarto check jupyter` commands in the terminal it works properly.

![correct working](https://github.com/quarto-dev/quarto-nvim/assets/31240856/b1adaad3-5876-4e88-b894-52f39f13d859)

But when I am inside neovim, it gives error: `Jupyter is not available`. Here the path for python is not correct. It is not using the venv python.

![error](https://github.com/quarto-dev/quarto-nvim/assets/31240856/2d4e90ce-6d57-4129-a1b3-c65db3417d2d)

![error2](https://github.com/quarto-dev/quarto-nvim/assets/31240856/6e580056-4180-4127-8516-b0704d221812)

If I run `which python` in neovim, it shows the correct venv python.

I am getting similar error when using fresh install of quarto-nvim-kickstarter.

**Comment by jmbuhr** [comment]
`:QuartoPreview` uses `:tabedit term://...` and according to the documentation o `:h terminal` this should inherit the environment variables from the environment in which nvim was started. It does so on my machine (linux), but I don't have access  to a mac to test this on iOS.
Can you test the following in your terminal:
```
python -m venv .venv
source .venv/bin/activate
which python
nvim a.qmd
```

in nvim:

```
:tabedit term://which python
```

**Comment by Mayur1009** [comment]
Output for `:tabedit term://which python`:
```
/Users/mayurks/new/.venv/bin/python

[Process exited 0]
```
But output for `quarto check jupyter`:
```
Quarto 1.4.551
[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .venv. Did you forget to activate it?


[Process exited 0]
```

**Comment by jmbuhr** [comment]
Where did you run `quarto check jupyter`?

**Comment by Mayur1009** [comment]
in neovim  `:tabedit term://quarto check jupyter`

**Comment by Mayur1009** [comment]
same here

**Comment by Mayur1009** [comment]
If I look at paths, 
- outside neovim:
```
/Users/mayurks/new/.venv/bin /opt/homebrew/sbin /opt/homebrew/bin /opt/homebrew/opt/fzf/bin /usr/local/bin ......
``` 

- inside neovim:
```
/opt/homebrew/bin /Users/mayurks/.local/share/nvim/mason/bin /Users/mayurks/new/.venv/bin /opt/homebrew/sbin /usr/local/bin 
```

For some reason, the order of the path is changing. And, I think quarto uses the python found in the first entry of the path.

So if I manually prepend `$VIRTUAL_ENV/bin` to the path inside neovim, then everything works without any errors.

**Comment by jmbuhr** [comment]
Looks like homebrew insists on being first

**Comment by Mayur1009** [comment]
Yes, because of how fish sets the PATH. This may be specific to fish and homebrew.

But shouldn't quarto be using the same python that is returned by `which python`, instead of using the first one found in the path?

**Comment by jmbuhr** [comment]
That's literally what gnu `which` does: Search the PATH and return the path of the first match. See `man which`.
