### ISSUE TITLE
error:  "method textDocument/documentHighlight is not supported by any of the servers registered for the current buffer"

### ISSUE THREAD

**Issue by hopezh** [quarto-dev/quarto-nvim#125]
As shown below, I got this error popping out constantly when editing a qmd file, after I update my neovim and lazyvim config:

`method textDocument/documentHighlight is not supported by any of the servers registered for the current buffer`

![image](https://github.com/quarto-dev/quarto-nvim/assets/23435810/4bff6465-5598-4afc-ae9a-28a8e56b624f)

Following [suggestion](https://www.reddit.com/r/neovim/comments/qhh4qr/nvimlspconfig_error_method_textdocumentcodeaction/) of neovim users, I used `autocmd CursorHold` command, and the output is:

![image](https://github.com/quarto-dev/quarto-nvim/assets/23435810/47eae7b9-86b5-4cf0-bc63-db9589922c10)

But I still don't know what is causing this error, which doesn't show up when editing other types of file, such as python or js. 

Seems `marksman` and `pyright` are attached to the current buffer:'

![image](https://github.com/quarto-dev/quarto-nvim/assets/23435810/f6c92007-d85e-4d6f-87b0-6ec4e1c4d25f)

Help is appreciated. 

Neovim: 0.10.0
Lazyvim: 11.4.1
quarto-nvim: commit 67e0902

**Comment by jmbuhr** [comment]
Different issue, but my troubleshooting advice here still applies: https://github.com/quarto-dev/quarto-nvim/issues/124#issuecomment-2102176553

**Comment by hopezh** [comment]
> I can not provide troubleshooting for all Neovim distributions (my tips for this are collected here: https://youtu.be/w1Dyh7jyT5Q), but am happy to help if you can provide a minimal reproducible example.

Thanks, @jmbuhr for your kind help. 

Before I figure out how to create a minimal reproducible example, and if you have time, kindly check this nvim config [oatvim07](https://github.com/hopezh/oatvim07) I just created that can reproduce the issue for the `test.qmd` file in the `test` folder.

**Comment by hopezh** [comment]
> Have you tried a bisect or a minimal config? Or the kickstarter config I provide.

Ok, I cloned your [lazyvim-starter-for-quarto](https://github.com/jmbuhr/lazyvim-starter-for-quarto), and added a `test.qmd` file in the `test` folder.

And the video below shows the error message when using this config to edit a `qmd` file:

https://github.com/quarto-dev/quarto-nvim/assets/23435810/a5e5df1b-015e-4ba0-b831-bb6821f6d810

**Comment by jmbuhr** [comment]
Interesting. I should remove that repo, as I can't maintain a config I have no control over.

I meant https://github.com/jmbuhr/quarto-nvim-kickstarter/

Did you follow the other troubleshooting advice in my linked comment?

**Comment by jmbuhr** [comment]
Looks like those plugins don't work on Windows out of the box, you can check out their readmes or simply disable them.

**Comment by hopezh** [comment]
> Looks like those plugins don't work on Windows out of the box, you can check out their readmes or simply disable them.

Noted with thanks. I'll follow ur suggestions on troubleshooting and see if I can isolate the source of error. 

Anyway, it's great that I can at least use your kick-starter config to work on `quarto` files smoothly.

**Comment by hopezh** [comment]
Hi @jmbuhr , the issue as reported has been resolved in the latest version of `lazyvim`, as discussed [here](https://github.com/LazyVim/LazyVim/issues/3246#issuecomment-2127449147).  

Thank you for your patience and advice.
