### ISSUE TITLE
Broken Syntax Highlighting for Code Annotation Block?

### ISSUE THREAD

**Issue by jeromecst** [quarto-dev/quarto-nvim#126]
Hi,

I feel like inserting a code annotation block will break the syntax highligtning for everything declared below it.

With the code block:
![image](https://github.com/quarto-dev/quarto-nvim/assets/39860768/db7b4c48-ff6a-474f-b282-0b3f283751f5)

Without:
![image](https://github.com/quarto-dev/quarto-nvim/assets/39860768/fb90189b-c1b9-4e94-9775-6058147b9583)

Everything seems fine with HTML Code blocks (but this is not what I'm trying to achieve)
![image](https://github.com/quarto-dev/quarto-nvim/assets/39860768/ce6be513-3e1f-460b-82dd-8abbfd436958)

**Comment by jmbuhr** [comment]
Something is certainly broken here, but I can not troubleshoot your personal configuration (because I don't have it and if I did I would quickly run out of time trying to do so for everyone).

Do you have treesitter configured correctly?

**Comment by jeromecst** [comment]
Thanks for pointing out where to look. Posting the solution if anybody is looking for the answer, add this option to treesitter:

```lua
highlight = {
    enable = true,
},
```

(I'm not sure why it's not enabled by default tho)
