### ISSUE TITLE
`run_below()` and `run_above()` prompt for a kernel on every cell

### ISSUE THREAD

**Issue by serhez** [quarto-dev/quarto-nvim#129]
When using `molten` and no kernel has been chosen yet, running the functions `run_below()` and `run_above()` (and perhaps `run_all()`, as I haven't tested it) prompt the user for the desired kernel on every cell. Instead, running these functions should just prompt the user for choosing a kernel in the first cell being run.

**Comment by jmbuhr** [comment]
@benlubas Could this be done in molten, as this effectively just calls `MoltenEvaluateRange`?

**Comment by benlubas** [comment]
That's probably a molten bug... You can open a bug report over there

**Comment by serhez** [comment]
I will, thanks!
