### ISSUE TITLE
Quarto tries to run R cell as python

### ISSUE THREAD

**Issue by Unaimend** [quarto-dev/quarto-nvim#130]
Hello, first of all thanks for the great plugin.

I have the problem that Quarto tries to execute the Cell that contains Line 34 as python instead of R code. Any ideas why? Is this a problem with molten?
![image](https://github.com/quarto-dev/quarto-nvim/assets/7808379/273d9aee-3720-44bf-a220-7db779b6f986)

**Comment by jmbuhr** [comment]
Looks like you have set molten as your code runner, but don't have a jupyter kernel for R installed, so it doesn't come up as an option.

**Comment by Unaimend** [comment]
That was indeed the problem. Thank you for your help
