### ISSUE TITLE
Error when trying to run `run_cell()`

### ISSUE THREAD

**Issue by vandalt** [quarto-dev/quarto-nvim#137]
I get the following error when trying to use `run_cell()` after the latest `otter.nvim` (which makes configuration much nicer btw, thanks a lot! :slightly_smiling_face:)

```lua
E5108: Error executing lua: ...l/share/nvim/lazy/quarto-nvim/lua/quarto/runner/init.lua:87: attempt to index field '_
otters_attached' (a nil value)                                                                                       
stack traceback:                                                                                                     
        ...l/share/nvim/lazy/quarto-nvim/lua/quarto/runner/init.lua:87: in function 'run'                            
        ...l/share/nvim/lazy/quarto-nvim/lua/quarto/runner/init.lua:111: in function 'run_cell'                      
        /home/vandal/.config/nvim/lua/plugins/repl.lua:182: in function </home/vandal/.config/nvim/lua/plugins/repl.l
ua:181>                   
```

It seems that `_otters_attached` was removed from the `otter.nvim` source code in the latest update. I'm looking at it right now to understand further, but wanted to point it out here as the fix is probably more obvious to you.

Thanks!

**Comment by jmbuhr** [comment]
Thanks! That was an oversight by me, I had renamed some things in otter.nvim and forget it here.
