### ISSUE TITLE
Publish to luarocks

### ISSUE THREAD

**Issue by flexagoon** [quarto-dev/quarto-nvim#140]
Please publish this plugin to https://luarocks.org/ to make it natively available with [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim).

You can find a guide here:

https://github.com/nvim-neorocks/sample-luarocks-plugin

**Comment by flexagoon** [comment]
@jmbuhr why was this closed? It doesn't seem like the plugin is published

**Comment by jmbuhr** [comment]
Yes. I appreciate the efforts, but I don't have the bandwidth to support multiple release endpoints. That's why I focus only on the things I can actively maintain. And for other plugin managers I don't have to actively do something.
