### ISSUE TITLE
`:QuartoSend` (with `molten.nvim` as runner) does not play well with `hydra.nvim`.

### ISSUE THREAD

**Issue by kalyanoliveira** [quarto-dev/quarto-nvim#141]
Pretty much what the title says. When trying to send `:QuartoSend` through neovim's command line via a "hydra" from [hydra.nvim](https://github.com/anuvyklack/hydra.nvim), neovim tells me that `vim.fn.MoltenEvaluateRange` does not exist. But when I run `:QuartoSend` manually (after re-opening neovim), everything works.

I've made a ~ 9 minute video explaining the issue in detail, as I thought it might be easier to demonstrate it in this manner: a stream of screenshots played one after the other rather than standalone ones.

[Temporary link to video explaining the issue](https://1drv.ms/u/s!AkYChCr011Dcht1VpoGriYtuVnLmvg?e=afSVKO) (expires in 1 week).

My entire [neovim configuration can be found here](https://github.com/kalyanoliveira/neovim-config).

I've said in the video that I believe that this issue belongs to [quarto-nvim](https://github.com/quarto-dev/quarto-nvim) because of the error that I was getting. 

In retrospect, though, perhaps it would also be suitable to discuss it in [hydra.nvim](https://github.com/anuvyklack/hydra.nvim)? Not sure if the folks over there would know much about quarto + molten and all that. 

Maybe I could even create an issue in [molten.nvim](https://github.com/benlubas/molten-nvim), since that's where I got the hydra code for (as per the video, in [Notebook-Setup.md](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md)).

Not sure, let me know if there's some more appropriate place to discuss this.

Also here's [that hydra configuration markdown guide for navigating and executing ipynb's](https://github.com/quarto-dev/quarto-nvim/wiki/Integrating-with-Hydra) that I showed in the video.

**Comment by jmbuhr** [comment]
Sounds more like a molten issue (so I'm pinging @benlubas already).

Note: I think people generally prefer issues with code and error messages one can read at a glance over 9 minute long videos.

On a different sidenote to @benlubas: Are you still actively using hydra? If not, I think we should remove the guide from the wiki as we can't guarantee that it stays up-to-date. And it seems very specific to one personal setup anyways, so maybe there is a better place for it.

**Comment by benlubas** [comment]
I am using Hydra. My setup still works and can be found [here](https://github.com/benlubas/.dotfiles/blob/main/nvim%2Flua%2Fbenlubas%2Fhydra%2Fnotebook.lua).


If you would like to open an issue on moltens repo please provide the error as text and upload screenshots and videos to GitHub so they display in the issue.

**Comment by kalyanoliveira** [comment]
This was my first time opening an issue, sorry about the long video guys, will take into account. Also I'll take all this over to [molten.nvim](https://github.com/benlubas/molten-nvim).

**Comment by kalyanoliveira** [comment]
I'll just add this last comment to this closed issue in case anyone runs into it as well: I deleted hydra.nvim with Lazy, and reinstalled it again, and that seemed to fix everything. Not a single change to my codebase either. Very weird.

**Comment by benlubas** [comment]
It's likely you just had an older version of the plugin that had a bug. Glad it's fixed!
