### ISSUE TITLE
Indentation Issues in Python Code Chunks

### ISSUE THREAD

**Issue by 00y300** [quarto-dev/quarto-nvim#142]
Hello @jmbuhr, I am having indentation problems with Pythonhunks. I was watching your Kickstarter videos, and you mentioned some indentation plugins can handle this. Here is a screen recording and tab/shift setup in my config. 

https://github.com/user-attachments/assets/34ee90e7-eb16-4b40-859e-566ea0b05d3f
### **Shift/Tab Setup**
```lua
local tabsize = 2
vim.opt.expandtab = true
vim.opt.shiftwidth = tabsize
vim.opt.tabstop = tabsize 
```

**Comment by jmbuhr** [comment]
That's not a quarto-nvim issue. And you have set tabsize to 2 and it indents by 2, seems correct.
