### ISSUE TITLE
Possible fix for LSP Error : Too Many Blank Lines.

### ISSUE THREAD

**Issue by Sumedh-G** [quarto-dev/quarto-nvim#144]
**The Problem** : To my current understanding, quarto allows for integrating code into .qmd files by creating invisible buffers for each code chunk, where everything outside the chunk in replaced with blank lines. This causes the LSP linters (tested in python) to show a warning for leaving too many blank lines in the code. 

![image](https://github.com/user-attachments/assets/74ae7a98-2096-47cb-b3a2-a87ebffe2bac)

**The suggested fix**: Instead of using blank lines, use empty comments for that language so that all previous lines still exist and the line numbers are preserved, but ignored by the LSP. Thus this will keep the linters functionality to stay inside code chunks only.

![image](https://github.com/user-attachments/assets/8829a24d-8c0e-4dc3-8fc8-30b1969354a9)
As you can see, commented lines do not trigger the linter.

**Possible Benefits**: Instead of creating multiple invisible buffers, the file can simply be structured so that all other content is ignored with use of comments. This will possibly help ai based completion to be more reliable by using commented lines as valuable context (which in most cases will be explaining the code), and also allows for plugins to generate markdown right into the file(maybe?) using comments like documentation generation.

**Comment by jmbuhr** [comment]
I appreciate the effort, but this doesn't solve the issue, as other languages or linters may just as well warn about empty comments and opens up different edge cases.

The best solution remains to tell your linter to ignore that warning type as shown in the readme. In your case it looks like ruff, which can just take a list of error codes to ignore. You can see the code next the the warning.

As to your AI-usecase: You can just enable whatever AI plugins you are using for quarto files, which gives the LLM all the context. For example I sometimes use copilot. It does sometimes create extra closing code chunk delimiters, but other than that it works. Your approach does not remove the need for one invisible buffer per language.

**Comment by Sumedh-G** [comment]
I see, can't disagree with any of your points and yes that is what I am doing currently. Just thought I could share my 2 cents. I am loving the plugin so far. Keep up the good work!
