### ISSUE TITLE
Inserting newline when sending cell content to ipython

### ISSUE THREAD

**Issue by mirelois** [quarto-dev/quarto-nvim#149]
I'm using kitty and sending code to an ipython pane using quarto with the slime backend.

The issue i'm having is that when the cell content is a python for loop, the code sent does not run until Enter is pressed on the ipython pane.

For example, this cell:
```python
for i in range(100):
    print(i)
```

results in this output:
```
In [22]: 
    ...: for i in range(100):
    ...:     print(i)
    ...: 
```
and the code does not run.

This is my slime config:
```lua
vim.g.slime_target = "kitty"
vim.g.slime_bracketed_paste = 1
vim.g.slime_python_ipython = 1
```

**Comment by mirelois** [comment]
I've looked into the source code and found that changing this line in the '/lua/quarto/runner/slime.lua' file:
```lua
vim.fn['slime#send'](text_lines )
```
to:
```lua
vim.fn['slime#send'](text_lines .. '\r')
```
seems to fix the issue for me is this the correct solution or is there a better way of doing it?

**Comment by jmbuhr** [comment]
`slime` has a recommended overwrite for sending python, but this doesn't get activated automatically when in a quarto filetype (only in python). My solution to this such that it works for all languages in Quarto is this: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/2c537e52dcbcc8ad1876fc0be5cd638666f0915c/lua/plugins/quarto.lua#L48-L60

It also includes some magic for documents that contain both R and python code, which you may not need.

**Comment by mirelois** [comment]
This did work although a note for anyone who sees this i had to turn bracketed paste off
