### ISSUE TITLE
Disabling render on save in nvim

### ISSUE THREAD

**Issue by rrgalvan** [quarto-dev/quarto-nvim#155]
I am very happy using quarto in nvim. 

But I would like to disable automatic rendering of .qmd files when the document is saved, because rendering takes a lot of time for some of my documents.

I tried writing
```
editor: 
  render-on-save: false
```
in the header of the document. No success. Any idea?

**Comment by jmbuhr** [comment]
I just added two user commands in https://github.com/quarto-dev/quarto-nvim/pull/157, QuartoPreviewNoWatch and QuartoUpdatePreview, the first starts the preview server without watching inputs (i.e. it doesn't re-render on save) and the second is for manually sending the re-render request to the server. Let me know if that works for you :)

**Comment by jmbuhr** [comment]
Plus https://github.com/quarto-dev/quarto-nvim/pull/159 to detect `render-on-save: false` automatically.

**Comment by rrgalvan** [comment]
Thank you very much,

now `render-on-save:false` works like a charm!

Comment: for this option to be recognized, I need to close the buffer and open it again (not a big deal).

**Comment by jmbuhr** [comment]
This is unexpected, the header should be scanned every time `QuartoUpdatePreview` is called. Was it just because the update had to go through or is this still the case?

**Comment by rrgalvan** [comment]
I think this issue is not related to the update. After updating the plugin (I am using Lazy.nvim), I close nvim and open it again with the following file:

```
---
title: "Quarto Test"
---

Testing `render-on-save: false`

```{python}
x = 0
x
```
```

Then I call `QuartoPreview` and everything works: if I modify one line (I write `x = 1`) and save the buffer, the changes are not rendered.

But if I set `render-on-save: true` in the header, changes are still not rendered.

More info, if now I call :QuartoUpdatePreview from the command line the changes are rendered and, from this moment on, changes will be rendered whenever I modify and save.

**Comment by jmbuhr** [comment]
`render-on-save` changes how the preview server is started, but it can not change a running server.

**Comment by rrgalvan** [comment]
OK, I understand. Tank you again!!

**Comment by rrgalvan** [comment]
Maybe the workflow would be more easy to understand the if you rename the command "QuartoUpdatePreview" to "QuartoParseAndPreview", "QuartoApplyHeadder" or something like that.

**Comment by jmbuhr** [comment]
QuartoUpdatePreview has nothing to do with the header, it just sends the command to re-render the preview. The header is only relevant for how the preview server is started. Maybe `QuartoRerenderPreview` would be a better name, but Update is more general.

**Comment by rrgalvan** [comment]
OK, thank you again
