### ISSUE TITLE
Issue when attempting to add the quarto.runner module

### ISSUE THREAD

**Issue by Veltair-D** [quarto-dev/quarto-nvim#156]
Using the kickstarter quarto configuration. Trying to use molten as code runner (not too fond of slime). Try to use the quarto.runner module. Error below appears when opening nvim.

What am I doing wrong? I really want to know. My nvim config is [here](https://github.com/user-attachments/files/18154554/nvim_backup.zip)

![Image](https://github.com/user-attachments/assets/60475e27-f2ac-4aeb-8b6d-f469b8602b1a)

**Comment by jmbuhr** [comment]
I'm not downloading a random zip file. How did you configure quarto-nvim?

**Comment by Veltair-D** [comment]
I used the kickstarter config. I added the following to the end. The rest is default (except I commented out the slime config)

```
  vim.keymap.set('n', '<localleader>rc', require('quarto.runner').run_cell, { desc = 'run cell', silent = true }),
  vim.keymap.set('n', '<localleader>ra', require('quarto.runner').run_above, { desc = 'run cell and above', silent = true }),
  vim.keymap.set('n', '<localleader>rA', require('quarto.runner').run_all, { desc = 'run all cells', silent = true }),
  vim.keymap.set('n', '<localleader>rl', require('quarto.runner').run_line, { desc = 'run line', silent = true }),
  vim.keymap.set('v', '<localleader>r', require('quarto.runner').run_range, { desc = 'run visual range', silent = true }),
  vim.keymap.set('n', '<localleader>RA', function()
    require('quarto.runner').run_all(true)
  end, { desc = 'run all cells of all languages', silent = true }),

```

**Comment by jmbuhr** [comment]
I see. See how the quarto module is only loaded for the quarto filetype: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/c23d86a5686bc846ea5c6a1a09542bb97abfed14/lua/plugins/quarto.lua#L6
My guess is that you are attempting to use it directly in your init.lua or another immediately evaluated module. You can either move it to a `config` function for the plugin or make it not lazy-loading by removing the `ft` requirement.
