### ISSUE TITLE
Trouble getting started with the plugin.

### ISSUE THREAD

**Issue by albertlunde123** [quarto-dev/quarto-nvim#19]
I have installed the plugin using packer. I have put the following in my plugins.lua file,

`return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use { 'quarto-dev/quarto-nvim',
  requires = {'neovim/nvim-lspconfig'}
}
end)`

Running PackerCompile and then PackerInstall, installs the packages without complaint. However when i open a *.qmd file I am immediatly greeted with the following error,

`Error executing Lua callback: ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:79:
 attempt to index field 'config' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:79: in function 'updateLa
nguageBuffers'
        ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:224: in function <...m/si
te/pack/packer/start/quarto-nvim/lua/quarto/init.lua:222>`

Any idea what is going on?

**Comment by jmbuhr** [comment]
oh, that is a design flaw on my end. In the process of making the plugin more configurable I made things that run automatically (`plugin/quarto.lua`) depend on the plugin being configured (with `require'quarto'.setup`), see the config section in the readme

**Comment by jmbuhr** [comment]
This means in the state right now you have to call the setup function in your own neovim config. For example, this is what I have in my own configuration right now:
https://github.com/jmbuhr/.dotfiles/blob/f4c68b30883cdf6efd555a44cd73ad78eb26033e/nvim/.config/nvim/lua/plugin-config/misc.lua#L85-L96

**Comment by jmbuhr** [comment]
The above commit fixes this, thank you for the find!

**Comment by albertlunde123** [comment]
Thanks! I have a dumb question..
How i exactly do i call the setup function?
I have a misc.lua with the content you linked to (only the last part concerning Quarto).

Also, the preview now works! However it still throws following error whenever i run :QuartoPreview

`Error executing Lua callback: ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:79:
 attempt to index field 'config' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:79: in function 'updateLa
nguageBuffers'
        ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:224: in function <...m/si
te/pack/packer/start/quarto-nvim/lua/quarto/init.lua:222>`

**Comment by jmbuhr** [comment]
Are you sure you mean `QuartoPreview` and not `QuartoActivate`? The latter would indeed rely on some configuration. About your neovim configuration: I haven't updated the example kickstart configuration for the new features (hence the link to my personal dotfiles earlier), but I will create an updated one tomorrow that can help you get started with configuring your neovim with lua. The misc.lua file has no special meaning, it is just how I organized my plugin configuration and only gets executed because I require it in my init.lua file, so I suspect yours doesn't get loaded.

**Comment by jmbuhr** [comment]
You may also have to run `PackerSync` to update all plugins

**Comment by jmbuhr** [comment]
Oh, and thank you for your input. There are no dumb questions and if something doesn't feel obvious it is an opportunity for me to improve the user experience. And before I am confident enough to put a 1 as the major version number there is plenty of room to tinker with those things

**Comment by albertlunde123** [comment]
Hey! I made the mistake of running before walking.. I started over and was a bit more meticulous. Everything works as it should now. Thank you for the help!

**Comment by jmbuhr** [comment]
No worries, glad you got it running! Means more real-life tests for me :)

**Comment by jmbuhr** [comment]
also let me know if you have ideas or requests for features. Sometimes there are things I haven't thought about implementing because they sound super hard at first glance, but may turn out easy on second thought. And sometimes they are the opposite...

**Comment by PMassicotte** [comment]
Hi there. I am trying to get started with this plugin using Packer. However, I am getting this error: 

```
Error detected while processing :source (no file):
E5108: Error executing lua [string ":source (no file)"]:1: module 'quarto' not found:                                                                                                 
        no field package.preload['quarto']
        no file './quarto.lua'
        no file '/usr/share/luajit-2.1.0-beta3/quarto.lua'
        no file '/usr/local/share/lua/5.1/quarto.lua'
        no file '/usr/local/share/lua/5.1/quarto/init.lua'
        no file '/usr/share/lua/5.1/quarto.lua'
        no file '/usr/share/lua/5.1/quarto/init.lua'
        no file '/home/xxx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/quarto.lua'
        no file '/home/xx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/quarto/init.lua'
        no file '/home/xx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/quarto.lua'
        no file '/home/xxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/quarto/init.lua'
        no file './quarto.so'
        no file '/usr/local/lib/lua/5.1/quarto.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/quarto.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/xxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/quarto.so'
stack traceback:
        [C]: in function 'require'
        [string ":source (no file)"]:1: in main chunk
```

My configuration file is simply as this one: https://github.com/jmbuhr/.dotfiles/blob/f4c68b30883cdf6efd555a44cd73ad78eb26033e/nvim/.config/nvim/lua/plugin-config/misc.lua#L85-L96

Any ideas on what I am missing?

Thank you!

**Comment by jmbuhr** [comment]
that looks like an old version of my personal dotfiles, you might want to check out the latest configuration as specified here: https://github.com/quarto-dev/quarto-nvim#setup: 
https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/main/lua/plugins/quarto.lua
