### ISSUE TITLE
setup() is required

### ISSUE THREAD

**Issue by jalvesaq** [quarto-dev/quarto-nvim#24]
The readme says "if you are fine with the defaults you don't have to call the setup function". However, if I don't call the setup function, I get the error: "attempt to index field 'config' (a nil value)".

**Comment by jmbuhr** [comment]
When do you get this error? I will clarify in the readme that `QuartoPreview` does not need the setup, but diagnostics and lsp features need to be set up.

**Comment by jmbuhr** [comment]
The readme should reflect the current state better now, thanks for the report. Let me know if this clears it up for you as well.

**Comment by jalvesaq** [comment]
Thanks for the quick fix!
