### ISSUE TITLE
Integrating quarto with LunarVim

### ISSUE THREAD

**Issue by AngelBerihuete** [quarto-dev/quarto-nvim#29]
Hi @jmbuhr ! Congrats for this wonderful plugin! I'm trying to use it in [LunarVim](https://github.com/LunarVim/LunarVim). I have followed the instructions in quarto-vim and in LunarVim to add plugins, but I obtain the following error when try to use QuartoPreview.

Please, any clue to resolve this error?

```
Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:26: no parser for 'markdown' language, see :help t
reesitter-parsers                                                                                                                       
stack traceback:                                                                                                                        
        [C]: in function 'error'                                                                                                        
        /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:26: in function 'require_language'                                      
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:38: in function '_create_parser'                                                 
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'                                                     
        ...m/site/pack/packer/start/otter.nvim/lua/otter/keeper.lua:24: in function 'extract_code_chunks'                               
        ...m/site/pack/packer/start/otter.nvim/lua/otter/keeper.lua:60: in function 'sync_raft'                                         
        ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:88: in function <...m/site/pack/packer/start/quarto-nvim/lua/quarto/
```

**Comment by jmbuhr** [comment]
I am surprised, but it looks like LunarVim does come with the treesitter plugin but does not install any parsers by default (https://github.com/LunarVim/LunarVim/blob/c18cd3f0a89443d4265f6df8ce12fb89d627f09e/lua/lvim/core/treesitter.lua#L9)

You can simply run `:TSInstall markdown` or `:TSInstall all` or set it up like I do: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/660b41450ed92eafbd507b5a9cda66fd2d5dac71/lua/plugins/treesitter.lua#L4

**Comment by ktakanopy** [comment]
I having this problem but i receive 'no parser for quarto' ...

**Comment by jmbuhr** [comment]
You can try it with the kickstarter configuration and check what is different from yours:
https://github.com/jmbuhr/quarto-nvim-kickstarter

Potential things to look out for are: treesitter, quarto, otter.nvim, a neovim version >= 0.8.3
