### ISSUE TITLE
Alternative: I've created a syntax file for .qmd files, as an alternative

### ISSUE THREAD

**Issue by aemonge** [quarto-dev/quarto-nvim#35]
To have the `quarto` cli working, without any integration. I was looking only for syntax highlighting, so I've made this **syntax/quarto.vim** filetype, I hope it helps someone:

```
syntax match quartoPythonCodeDelimiter /```{.*}/ conceal
syntax match quartoPythonCodeStart /```{python}/ containedin=quartoPythonCode contains=quartoPythonCodeDelimiter

highlight link quartoPythonCodeDelimiter Conceal

runtime! syntax/markdown.vim
let s:cs_safe = b:current_syntax

unlet b:current_syntax
syntax include @Python syntax/python.vim
let b:current_syntax = s:cs_safe

syntax region quartoPythonCode start=/```{python}/ end=/```/ contains=@Python
```

**Comment by jmbuhr** [comment]
If you just want vim syntax highlighting and no neovim specific features, you can also use the quarto-vim extension, which does pretty much what your snippet does: https://github.com/quarto-dev/quarto-vim/blob/master/syntax/quarto.vim

Note: I hope you don't mind me closing this issue. It can still be found in searches and I prefer to keep only issues open that represent an actual task/bug/feature request etc.

**Comment by aemonge** [comment]
Nah, I don't mind at all !

In that file that you share, where is `PandocHighlight` defined?

**Comment by jmbuhr** [comment]
That's from the pandoc syntax plugin mentioned in the setup. I suppose if you don't like plugin managers, you can also copy and paste from there.
https://github.com/quarto-dev/quarto-vim#setup

**Comment by aemonge** [comment]
That's exaclty what I was looking for !

:bow: Thanks
