### ISSUE TITLE
[feat] add markdown language server

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-nvim#4]
Excited for: https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features/server

Once this goes live, we should add it to the recommended nvim configuration!

**Comment by xvzftube** [comment]
I am not sure if this is related, but I have a coc.nvim https://github.com/neoclide/coc.nvim  setup. I have coc-r-lsp and pyright installed. Would having a Markdown language server allow for syntax highlighting within code blocks?

**Comment by xvzftube** [comment]
For example 

```
---
title: "Test document"
jupyter: python3
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{python}
import pandas as pd
df = pd.read_csv("diamonds.csv")
df.query('color == "E"')
```

I would like python autocompletion when I am in the python block, but I would not want to say the entire document should be treated as a python file.

```

**Comment by jmbuhr** [comment]
You already get syntax highlighting with treesitter. See https://github.com/quarto-dev/quarto-nvim#recommended-plugins.

For a disccusion on autocompletion read https://github.com/quarto-dev/quarto-nvim/issues/2

For the reasons outlined in the issue above it is not as straighforward, but I think the plugin mentioned at the end has the greatest potential to become what we need (https://github.com/AckslD/nvim-FeMaco.lua/issues/20). But I havn't finished my PR for this feature.

For now, my workflow still uses RStudio with large computational notebooks with plots and other output, neovim with plain R and python code and neovim with quarto documents without much code.

**Comment by jmbuhr** [comment]
You can also experiment with my personal dotfiles, which include a bit more than just the kickstarter config I made: https://github.com/jmbuhr/.dotfiles/tree/main/nvim/.config/nvim

Like jumping between code blocks in plain R and python files separated by `#%%`
