### ISSUE TITLE
Trouble installing the plugin " module 'cmp.config.context' not found "

### ISSUE THREAD

**Issue by pierrecamilleri** [quarto-dev/quarto-nvim#40]
Hi, 

I tried to install the plugin with vim-plug and I get an error on neovim startup : 

```
E5113: Error while calling lua chunk: ...re/.vim/plugged/otter.nvim/lua/otter/tools/functions.lua:3: module 'cmp.config.context' not found:
        no field package.preload['cmp.config.context']
        no file './cmp/config/context.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/cmp/config/context.lua'
        no file '/usr/local/share/lua/5.1/cmp/config/context.lua'
        no file '/usr/local/share/lua/5.1/cmp/config/context/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/cmp/config/context.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/cmp/config/context/init.lua'
        no file './cmp/config/context.so'
        no file '/usr/local/lib/lua/5.1/cmp/config/context.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/cmp/config/context.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './cmp.so'
        no file '/usr/local/lib/lua/5.1/cmp.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/cmp.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...re/.vim/plugged/otter.nvim/lua/otter/tools/functions.lua:3: in main chunk
        [C]: in function 'require'
        /home/pierre/.vim/plugged/otter.nvim/lua/otter/keeper.lua:2: in main chunk
        [C]: in function 'require'
        /home/pierre/.vim/plugged/otter.nvim/lua/otter/init.lua:4: in main chunk
        [C]: in function 'require'
        /home/pierre/.vim/plugged/quarto-nvim/lua/quarto/init.lua:5: in main chunk
        [C]: in function 'require'
        /home/pierre/.vim/plugged/quarto-nvim/plugin/quarto.lua:1: in main chunk
``` 

I tried to run the plugin in isolation, and got the same error (not sure this is the right way, I am not so much of a nvim ninja): 
```sh
nvim -Nu <(cat << VIMRC
  set runtimepath+=~/.vim/plugged/quarto-nvim/
  set runtimepath+=~/.vim/plugged/nvim-lspconfig/
  set runtimepath+=~/.vim/plugged/otter.nvim/
VIMRC)
```

When I google `lua cmp` I get results for `nvim-cmp` plugin, which happens to be used in the quarto kickstarter plugin, so there may be some link ?

**Comment by jmbuhr** [comment]
It used to be just the completion functionality that relied on `nvim-cmp`, but I added a feature last week to enable the use of a fallback function for keybindings when not within a code chunk, which also relies on a function from `nvim-cmp`. I am now being more specific in the README about those dependencies, thanks for the catch!

Unfortunately neovim doesn't yet have a systematic way of specifying plugin dependencies, so we rely on the various package managers and thus provide example configurations for those.
The best way to see all the features of this plugin is with https://github.com/jmbuhr/quarto-nvim-kickstarter

**Comment by jmbuhr** [comment]
Yes, that's a fair point. I'll see if I can decouple the simple quarto preview functionality from the code completion and language server features!

**Comment by jmbuhr** [comment]
Small addition: In this case you don't have to worry about your config. cmp doesn't do anything if it's setup function is not called.
