### ISSUE TITLE
Parser not available for language "quarto"

### ISSUE THREAD

**Issue by jsantanders** [quarto-dev/quarto-nvim#49]
After installing the plugging with Packer and try to open a .qmd file I'm getting the following error:

```
Installation not possible: ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:52: Parser not available for language "quarto"
See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to add a new parser!
```

I've tried to install manually with

```
:TSInstall quarto
```

But I'm getting the same error.

I could be that I'm missing something?

**Comment by jmbuhr** [comment]
As of now we are still using the `markdown` treesitter parser for quarto, but between nvim 0.8 and the freshly releases 0.9 the way to specify that a certain filetype uses a certain parser moved from the `nvim-treesitter` plugin into a nvim core function.

As such it may be that you either have a too old or too new version of nvim-treesitter (or an unlucky combination of nvim-treesitter and neovim version). More on this here: https://github.com/quarto-dev/quarto-nvim/issues/48#issuecomment-1500689318

Tomorrow I should have the definitive solution for nvim 0.9 done. I won't merge straight away, but I'll make sure that the nvim 0.9 branches of my quarto plugins and the kickstarter config align.

**Comment by jsantanders** [comment]
Thanks, I do have nvim 0.8, later I will try downgrading nvim-treesitter.

**Comment by jmbuhr** [comment]
You can find the versions of the plugins you need in this branch: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/nvim-0.8.3/lua/plugins/quarto.lua
