### ISSUE TITLE
[bug] installing `quarto-nvim` with `vim-plug` does not expose `QuartoPreview` command

### ISSUE THREAD

**Issue by baggiponte** [quarto-dev/quarto-nvim#5]
I followed the instructions and added `quarto-nvim` as plugin with `vim-plug`:

```vim
call plug#begin('~/.config/nvim/plugged')
    Plug 'quarto-dev/quarto-nvim'
call plug#end()
```

Then saved, sourced and installed the plugin. However, the `QuartoPreview` command is not exposed.

**Comment by jmbuhr** [comment]
The command is only created when the setup function is called (see https://github.com/quarto-dev/quarto-nvim#usage). But I can see that it wouldn't pollute peoples namespaces too much if we always create the command when the plugin is just loaded.

**Comment by jmbuhr** [comment]
Let me check out how other plugins handle this.

**Comment by baggiponte** [comment]
Thank you for the reply! Now I understand that I misunderstood the usage instructions: I believed that the line `The setup function creates a user command ...` meant that the command was available. This means that I need to add to my `init.nvim` or `init.lua` the other lines - am I right?

```lua
local quarto = require'quarto'
vim.keymap.set('n', '<leader>qp', quarto.quartoPreview, {silent = true, noremap = true})
```

**Comment by jmbuhr** [comment]
These lines configure a keybinding. What you want is the lua code `require'quarto'.setup()`

I kept it in the setup function to be prepared for future customization, but let me see if I can export the UserCommand without the setup function as well.

**Comment by jmbuhr** [comment]
This should work the way you expected it to work now. Can you update and test with vim-plug?

**Comment by baggiponte** [comment]
Now it works, thank you!
