### ISSUE TITLE
treesitter-text-objects queries overwritten for python, r, bash, markdown

### ISSUE THREAD

**Issue by mr-majkel** [quarto-dev/quarto-nvim#58]
Hi @jmbuhr,

it seems that with some recent updates to treesitter or treesitter-text-objects, the `queries/` folder in `quarto-nvim` plugin seems to be overwriting the `treesitter-text-objects`. I have found [this issue](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/370) directly pointing to the definitions in the `queries` folder as a culprit of text objects not working. One of the `text-objects` maintainers says that:

> In the quarto-nvim plugin, there's queries/python/textobjects.scm which completely overwrites the nvim-treesitter-textobjects's queries. If you want to extend the queries, you need to have it on after/queries/python/textobjects.scm. For some reason, the plugin just uses both files, and maybe the previous version of this plugin ignored this issue.

I'm not sure if such behavior of treesitter is not a regression, though. According to the official treesitter [docs](https://github.com/nvim-treesitter/nvim-treesitter#adding-queries):

>All queries found in the runtime directories will be combined. By convention, if you want to write a query, use the queries/ directory, but if you want to extend a query use the after/queries/ directory.

My reading of this is that the queries/ directories of all plugins should be somehow combined, but not overwriting each other.

Still, I can confirm that deleting the queries/ folder in quarto-nvim fixes the issue. Maybe these queries can be moved to after/queries folder?

I'm running nvim 0.9.0 and the freshest version of the mentioned packages. I'm running my own custom config (I'm not using the kickstarter-quarto-nvim plugin)

**Comment by jmbuhr** [comment]
This is a mistake on my side indeed, I will fix this tomorrow
