### ISSUE TITLE
Module lspconfig.util not found

### ISSUE THREAD

**Issue by svilupp** [quarto-dev/quarto-nvim#7]
First of all, thank you for putting it together!

I am having trouble using the plugin together with other LSP servers. When I follow installation + config instructions, I get an error about 'lspconfig.util' file missing (see the error below).

There is a workaround I found (by installing nvim-lsp-installer) but that breaks my LSP settings, as it doesn't load the other LS configs properly.

I have tried to install Quarto-nvim (with Packer):
```
use({
  "quarto-dev/quarto-vim",
  requires = {
      {"vim-pandoc/vim-pandoc-syntax"},
  },
  ft = {"quarto"},
})
use { 'quarto-dev/quarto-nvim',
  requires="neovim/nvim-lspconfig",
  config = function ()

    require'quarto'.setup()

   local quarto = require'quarto'
    vim.keymap.set('n', '<leader>qp', quarto.quartoPreview, {silent = true, noremap = true})
  end
}

```
The error I get upon start up:
> packer.nvim: Error running config for quarto-nvim: ...m/site/pack/packer/start/quarto-nvim/lua/quarto/init.lua:4: module 'lspconfig.util' not found:
^Ino field package.preload['lspconfig.util']
^Ino file './lspconfig/util.lua'
^Ino file '/opt/homebrew/share/luajit-2.1.0-beta3/lspconfig/util.lua'
^Ino file '/usr/local/share/lua/5.1/lspconfig/util.lua'
^Ino file '/usr/local/share/lua/5.1/lspconfig/util/init.lua'
^Ino file '/opt/homebrew/share/lua/5.1/lspconfig/util.lua'
^Ino file '/opt/homebrew/share/lua/5.1/lspconfig/util/init.lua'
^Ino file '/Users/simljx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/lspconfig/util.lua'
^Ino file '/Users/simljx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/lspconfig/util/init.lua'
^Ino file '/Users/simljx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/lspconfig/util.lua'
^Ino file '/Users/simljx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/lspconfig/util/init.lua'
^Ino file './lspconfig/util.so'
^Ino file '/usr/local/lib/lua/5.1/lspconfig/util.so'
^Ino file '/opt/homebrew/lib/lua/5.1/lspconfig/util.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/Users/simljx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/lspconfig/util.so'
^Ino file './lspconfig.so'
^Ino file '/usr/local/lib/lua/5.1/lspconfig.so'
^Ino file '/opt/homebrew/lib/lua/5.1/lspconfig.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

I have found one solution, which is to install 'nvim-lsp-installer', but that unfortunately breaks all my lspconfig settings for my LSPs.
This is the command which leads to Quarto preview loading properly:
```
use({  "williamboman/nvim-lsp-installer",
        "neovim/nvim-lspconfig",
        setup = function()
            require("nvim-lsp-installer").setup {}
        end,
        after = "cmp-nvim-lsp",config=[[require('config.lsp')]] })
```

Any ideas would be appreciated!

**Comment by jmbuhr** [comment]
It does indeed rely on https://github.com/neovim/nvim-lspconfig (because it has a nice function to find the root directory of a project and I assumed most people use it for language server configuration anyways)

**Comment by jmbuhr** [comment]
I just updated the readme accordingly

**Comment by jmbuhr** [comment]
lspconfig itself only provides configuration helpers, so if you don't load it directly it shouldn't interfere with other ways of attaching language servers you might be using.

**Comment by svilupp** [comment]
I do have the nvim-lspconfig as a requirement, so I'm not sure why can Quarto not see the util script in it.
And I'm using it quite a bit and loading it via: 
`use({ "neovim/nvim-lspconfig", after = "cmp-nvim-lsp", config = [[require('config.lsp')]] })`


My issue is that Quarto-nvim cannot see it / use it. 
I even tried to load it with delayed execution to make sure it's not some Packer sequencing bug but it still gave an error.

Would you have any ideas how to debug what's happening?

**Comment by jmbuhr** [comment]
Are you loading it like that to optimize your startup time? Could you try simply installing it via `use` instead of things like `after`?

Can you require the lspconfig normally in your init,lua file? Can you access modules from it?

**Comment by jmbuhr** [comment]
You can also take a look at https://github.com/jmbuhr/quarto-nvim-kickstarter for inspiration.

**Comment by svilupp** [comment]
> Are you loading it like that to optimize your startup time? Could you try simply installing it via use instead of things like after?
That's required when using cmp for autocompletion.

> Can you require the lspconfig normally in your init,lua file? Can you access modules from it?
Yes, I can (once plugins are loaded). That's my new workaround (to call the quarto-nvim config after everything else is done)

> You can also take a look at https://github.com/jmbuhr/quarto-nvim-kickstarter for inspiration.
I have. That's how I came up with the original workaround.

> And did you make sure to PackerSync and/ or PackerCompile after sourcing your updated lua config?
Yes, every time.

I think we can close this issue - the more I play with it, the more it seems like a bug in Packer that it does not handle the dependency properly. 

My temporary solution will be loading the quarto-nvim config after ALL plugins are loaded, which works.

Thank you for your help!

**Comment by jmbuhr** [comment]
Alright, thanks for the report :)
And just a quick heads up since you are using quarto with lsp: My first implementation to get language diagnostics and lsp things for languages in quarto code blocks is currently very inefficient. So I don't recommend to activate it until I figured out how to make it not freeze neovim on a computer that is not super overpowered :see_no_evil:

**Comment by jmbuhr** [comment]
That makes a lot of sense, I was searching for such a workflow for python and R as well. Looking forward to a quarto native solution for this (https://github.com/quarto-dev/quarto-cli/issues/588)
