### ISSUE TITLE
Cannot use Quarto commands

### ISSUE THREAD

**Issue by carrascomj** [quarto-dev/quarto-nvim#76]
When I run `:QuartoPreview`, I get this:

```
E5108: Error executing lua ...g/.local/share/nvim/lazy/quarto-nvim/lua/quarto/init.lua:47: at
tempt to index field 'uv' (a nil value)                                                      
stack traceback:                                                                             
        ...g/.local/share/nvim/lazy/quarto-nvim/lua/quarto/init.lua:47: in function 'quartoPr
eview'                                                                                       
        [string ":lua"]:1: in main chunk
```

I am using the config https://github.com/jmbuhr/quarto-nvim-kickstarter/commit/dce6da4a371bc796bf8ec3f555dbc7c2b32f2266 as is (latest commit). It did not work with the previous commit or by installing quarto.nvim with its dependencies on my own config.

Nvim version:

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by carrascomj** [comment]
Found the culprit:  [`vim.uv` was deprecated in favor of `vim.loop`](https://neovim.io/doc/user/news.html#news-deprecations).

Maybe the version should be tied to `0.9.0` instead of `0.9.1`.

**Comment by jmbuhr** [comment]
The deprecation is the other way around. But I should have stuck with `loop` until nvim 0.10 is the stable version, just updated to soon.

**Comment by carrascomj** [comment]
You are completely right, I read it wrong. Changing uv for loop works on 0.9.1, for the most part.

**Comment by jmbuhr** [comment]
latest release has the fix now, thanks for the catch!
