### ISSUE TITLE
Using `{.rust}` instead of `rust` as the language for a code block removes treesitter highlighting

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-nvim#78]
In the screenshot below, on the left I'm using 

````
```rust
````

and on the right I'm using

````
```{.rust}
````

<img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-nvim/assets/1813121/848b38f9-5049-4057-a9ff-ab2f52927096">

Quarto extensions like https://github.com/shafayetShafee/line-highlight/ using the `{}` syntax to add attributes for the code blocks, e.g.:

````
```{.python source-line-numbers="3-4" .numberLines}
print("Hello world")

for name in ["Sam", "Jake"]:
    print(f"Hello {name}!")
```
````

Is there a way to make this syntax also work for syntax highlighting?

**Comment by jmbuhr** [comment]
Yes and no. Unfortunately, the current markdown parser keeps special symbols such as `.` and `=` as part of the language of the code block and as such does not find the correct language injection for highlighting, as no parser exists for `.rust` or e.g. `=html`, only `rust` and `html`.

However, there is a straightforward workaround. We can take advantage of the fact that we can add attributes to essentially anything in pandoc's (=quarto's) markdown (see https://quarto.org/docs/authoring/markdown-basics.html#divs-and-spans).
As such, we can take a regular, non-executable code block with the normal markdown syntax and just add our attributes in their own curly braces afterwards:

````
```rust {code-line-numbers="true" filename="example.rs"}
fn main() {
    println!("Hello world");
}
```
````

![image](https://github.com/quarto-dev/quarto-nvim/assets/17450586/a6ebfc8d-0373-4e3f-8068-b6cb3b4b8e32)

**Comment by kdheepak** [comment]
That seems like an elegant workaround! I’m assuming that it is equivalent to writing it with the `.rust` in the curly braces, right?

I do think this feature should be highlighted in the official documentation. I’ll submit a issue for that on the quarto docs page.

**Comment by einarpersson** [comment]
@jmbuhr Can this be used to enable syntax highlighting for raw html blocks? (that are to be rendered) as outlined [here](https://github.com/quarto-dev/quarto-nvim/discussions/183)
