### ISSUE TITLE
[BUG] `QuartoPreview`/`QuartoRender` fail to run unless `$PATH` is updated

### ISSUE THREAD

**Issue by baggiponte** [quarto-dev/quarto-nvim#8]
Hi! I don't really know which direction will quarto development take, but as of now `quarto` on macOS is installed under 
`/Applications/quarto/bin/quarto`. This means that, unless the user sets `export PATH="/Applications:$PATH`, the `QuartoPreview`/`QuartoRender` commands will fail.

If this behaviour is okay, I could write a PR to make this clearer in the docs. Otherwise, I believe this is the line/location where the magic happens:

https://github.com/quarto-dev/quarto-nvim/blob/7736a621a1c135a781fd3bb563c341b5f5f145c7/lua/quarto/init.lua#L38

I don't really know where quarto is installed on Windows, but I guess it would be easy to add a conditional ( e.g., if os is macOS, `local quarto_path = '/Applications/quarto/bin'`, else...) and make `local cmd = quarto_path .. '/quarto preview'`. I'd be glade to write this PR as well.

**Comment by dragonstyle** [comment]
As a part of installation on the Mac, we add the quarto bin path to the path via `.zshenv` and attempt to make a symlink to it as well (though since we attempt to make that in `/usr/local/bin/quarto` it often will not succeed and we'll instead silently use the path resolution instead).

**Comment by jmbuhr** [comment]
Thank you for the issue!
Yes, I am expecting quarto to be available on the `PATH`. This should be a reasonable assumption, because people that use neovim are very likely running quarto from the terminal (in which they also run neovim) anyways as well.

**Comment by baggiponte** [comment]
Thank you for the reply. Just to be sure: are you saying that as of now we shall just append /Applications to $PATH?

**Comment by jmbuhr** [comment]
Alright, looks like we can close this issue here then.
