### ISSUE TITLE
`QuartoPreview` with partial execution

### ISSUE THREAD

**Issue by egolep** [quarto-dev/quarto-nvim#83]
Maybe it's already possible and I'm not getting how to do it, but it would be great if we could have the `Quarto` preview to re-render only modified code cells or to just render the new ones.

If I get it correctly, this behavior is already present for VSCode:
https://quarto.org/docs/tools/vscode.html

**Comment by jmbuhr** [comment]
That's not a function of the editor, but rather the `quarto` cli tool directly. It depends on the code execution engine (see https://quarto.org/docs/computations/execution-options.html#engine-binding). For example, in a qmd with only python chunks, the jupyter engine is used. The jupyter server will be kept alive in the background while the preview is running and it will only re-execute code cells that have been changed. For a pure R qmd document, the knitr R package is used. This can also have caching (but it is not enabled by default, I belive), but the process has no way of being kept alive during the preview so there is some startup cost associated with re-rendering the changed code cells.

**Comment by egolep** [comment]
Then I am missing something, since everytime I save my `.qmd` file all cells get re-executed.
Should I run `QuartoPreview` with some parameters or something else?
For example, if I have a cell like:

```{python}
a = 0
for i in range(100_000_000):
    a+=1

print(a)
```

This get executed all the time, which is obviously time consuming. This is a toy example, but I hope this illustrate my problem.

**Comment by jmbuhr** [comment]
oh, my bad, the cache has to be enabled manually also for jupyter: https://quarto.org/docs/projects/code-execution.html#cache

**Comment by egolep** [comment]
Yeah I saw this page after your previous reply, but as far as I can understand, `jupyter-cache` does re-execute the whole notebook. It allows to re-run only one or some specific notebooks in a bigger project, but it doesn't work in a "cell-by-cell" fashion. And maybe this is the actual use case and I'm trying to bend Quarto to do something outside of its scope :P

**Comment by jmbuhr** [comment]
You are correct! I had falsely assumed jupyter did a similar caching to what R/knitr does. In that case it is only useful when working on the prose and markdown between the code chunks, I suppose. In that case the only true cell-by-cell caching would be in a jupyter notebook.

**Comment by egolep** [comment]
Yeah now I get why I didn't manage to get it working as I wanted.
Thanks for your patience and for your replies!

**Comment by jmbuhr** [comment]
On a more opinionated note: I don't think any computations that come close to being long-running should live in a notebook. This is what workflow managers are for.
Though to be fair, I am yet to come across something in the python ecosystem that I like quite as much as the `targets` package for `R`. Sometimes a bunch of python scripts and a `Makefile` are a good solution. Last time I needed it, I sort of ended up writing my own lighweight workflow management, which I do indeed control from a quarto notebook (in essence just bunch of functions that check if their output already exists before doing any computations).

**Comment by jmbuhr** [comment]
So do let me know if you come across something interesting in that realm! :)
