### ISSUE TITLE
I get a 

### ISSUE THREAD

**Issue by xvzftube** [quarto-dev/quarto-nvim#9]
When I run `:QuartoPreview` on the following file I get the error `ERROR: Cannot serve project of type 'default' (try using project type 'website').`

```
---
title: "ggplot2 demo"
project: 
  type: website
author: "Norah Jones"
date: "5/22/2021"
format: 
  html:
    fig-width: 8
    fig-height: 4
    code-fold: true
---

## Air Quality

@fig-airquality further explores the impact of temperature on ozone level.

```{r}
#| label: fig-airquality
#| fig-cap: Temperature and ozone level.
#| warning: false

library(ggplot2)

ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess"
)
```

```
ERROR: Cannot serve project of type 'default' (try using project type 'website').

[Process exited 1]
```

**Comment by jmbuhr** [comment]
The `project` yaml key is something quarto would expect in a quarto project not in the metadata of a single file. So I would expect an error. A quarto project is indicated by a `_quarto.yml` file, e.g. like here: https://quarto.org/docs/projects/quarto-projects.html#project-metadata

**Comment by xvzftube** [comment]
That worked!

So for each project I will have to add

```
project:
  type: website
```

I am guessing there is a setting where I can set that as a default. Is that true?

**Comment by jmbuhr** [comment]
quarto automatically creates a template `_quarto.yml` file if you create a projet from the command line with `quarto create-project` (https://quarto.org/docs/projects/quarto-projects.html). Check out the `--help` for this command to see the options. For example, you can pass  `--type website` to it.

**Comment by jmbuhr** [comment]
Closing this now, since it is unrelated to the neovim extension.
