### ISSUE TITLE
[Bug] Blocks UI on startup

### ISSUE THREAD

**Issue by benlubas** [quarto-dev/quarto-nvim#90]
I've noticed that when I open a `qmd` file with this plugin enabled, I have a second or two where I cannot move my cursor.

Disabling the plugin immediately removes this delay.  I'm wondering if anyone else has noticed a similar issue

**Comment by jmbuhr** [comment]
I have noticed this with certain iterations of pyright, a couple of versions where incredibly slow to start up. To me it seems the latest got a bit better.

The reasons this also affects this plugin is that it loads up a python file with your code if the document has python chunks. Can you confirm that you experience the same slowdown a) when opening a plain python file and b) **not** when opening a qmd fiel that contains no code or only e.g. R code, not python.

**Comment by benlubas** [comment]
Oh yup. Pyright is the problem, hopefully one of the other language servers will be better

Curious issue though, rust-analyzer is really slow to startup but it never seems to affect moving around the window.
