### ISSUE TITLE
Stylua formatting file

### ISSUE THREAD

**Issue by benlubas** [quarto-dev/quarto-nvim#94]
I've noticed that a lot of the code formatting conflicts with stylua defaults, it would be nice to have a stylua file so that my formatter doesn't take over the entire project

**Comment by jmbuhr** [comment]
I'm going with what the lua language server does in terms of formatting unless there is a major reason to introduce additional tooling.

**Comment by benlubas** [comment]
The language server formatting is very loose by default, so code style won't be consistent across the codebase without configuration, stylua is more opinionated (and more common in the neovim community). That said, the [default code formatter](https://github.com/CppCXY/EmmyLuaCodeStyle/blob/master/docs/format_config_EN.md) is configurable, so stricter code styling could be had without adding a new tool. 

Up to you of course

**Comment by jmbuhr** [comment]
ok, was super simple with stylua being available in Mason :)
